routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::prefix('gestione')->name('admin.')->middleware('auth')->group(function () {
    Route::get('/', 'DashboardController@index')->name('home');

    Route::get('/settings', 'SettingController@index')->name('settings');
    Route::post('/settings', 'SettingController@save');

    Route::get('/menues', 'MenuController@index')->name('menues');
    Route::post('/menues/json', 'MenuController@json')->name('menues_json');
    Route::get('/menues/form', 'MenuController@edit')->name('menues_form');
    Route::get('/menues/form/{id}', 'MenuController@edit');
    Route::post('/menues/form', 'MenuController@store');
    Route::post('/menues/delete', 'MenuController@destroy')->name('menues_destroy');
    Route::post('/menues/exchange', 'MenuController@exchange')->name('menues_exchange');

    Route::get('/news', 'NewsController@index')->name('news');
    Route::post('/news/json', 'NewsController@json')->name('news_json');
    Route::get('/news/form', 'NewsController@edit')->name('news_form');
    Route::get('/news/form/{id}', 'NewsController@edit');
    Route::post('/news/form', 'NewsController@store');
    Route::post('/news/delete', 'NewsController@destroy')->name('news_destroy');
    Route::post('/news/exchange', 'NewsController@exchange')->name('news_exchange');

    Route::get('/categories', 'CategoryController@index')->name('categories');
    Route::post('/categories/json', 'CategoryController@json')->name('categories_json');
    Route::get('/categories/form', 'CategoryController@edit')->name('categories_form');
    Route::get('/categories/form/{id}', 'CategoryController@edit');
    Route::post('/categories/form', 'CategoryController@store');
    Route::post('/categories/delete', 'CategoryController@destroy')->name('categories_destroy');
    Route::post('/categories/exchange', 'CategoryController@exchange')->name('categories_exchange');

    Route::get('/printareas', 'PrintAreaController@index')->name('printareas');
    Route::post('/printareas/json', 'PrintAreaController@json')->name('printareas_json');
    Route::get('/printareas/form', 'PrintAreaController@edit')->name('printareas_form');
    Route::get('/printareas/form/{id}', 'PrintAreaController@edit');
    Route::post('/printareas/form', 'PrintAreaController@store');
    Route::post('/printareas/delete', 'PrintAreaController@destroy')->name('printareas_destroy');
    Route::post('/printareas/exchange', 'PrintAreaController@exchange')->name('printareas_exchange');


    Route::get('/vgroups', 'VgroupController@index')->name('vgroups');
    Route::post('/vgroups/json', 'VgroupController@json')->name('vgroups_json');
    Route::get('/vgroups/form', 'VgroupController@edit')->name('vgroups_form');
    Route::get('/vgroups/form/{id}', 'VgroupController@edit');
    Route::post('/vgroups/form', 'VgroupController@store');
    Route::post('/vgroups/delete', 'VgroupController@destroy')->name('vgroups_destroy');
    Route::post('/vgroups/exchange', 'VgroupController@exchange')->name('vgroups_exchange');

    Route::get('/variations', 'VariationController@index')->name('variations');
    Route::post('/variations/json', 'VariationController@json')->name('variations_json');
    Route::get('/variations/form', 'VariationController@edit')->name('variations_form');
    Route::get('/variations/form/{id}', 'VariationController@edit');
    Route::post('/variations/form', 'VariationController@store');
    Route::post('/variations/delete', 'VariationController@destroy')->name('variations_destroy');
    Route::post('/variations/exchange', 'VariationController@exchange')->name('variations_exchange');

    Route::get('/addons', 'AddonController@index')->name('addons');
    Route::post('/addons/json', 'AddonController@json')->name('addons_json');
    Route::get('/addons/form', 'AddonController@edit')->name('addons_form');
    Route::get('/addons/form/{id}', 'AddonController@edit');
    Route::post('/addons/form', 'AddonController@store');
    Route::post('/addons/delete', 'AddonController@destroy')->name('addons_destroy');
    Route::post('/addons/exchange', 'AddonController@exchange')->name('addons_exchange');

    Route::get('/timetables', 'TimetableController@index')->name('timetables');
    Route::post('/timetables/json', 'TimetableController@json')->name('timetables_json');
    Route::get('/timetables/form', 'TimetableController@edit')->name('timetables_form');
    Route::get('/timetables/form/{id}', 'TimetableController@edit');
    Route::post('/timetables/form', 'TimetableController@store');
    Route::post('/timetables/delete', 'TimetableController@destroy')->name('timetables_destroy');
    Route::post('/timetables/exchange', 'TimetableController@exchange')->name('timetables_exchange');

    Route::get('/addresses', 'AddressController@index')->name('addresses');
    Route::post('/addresses/json', 'AddressController@json')->name('addresses_json');
    Route::get('/addresses/form', 'AddressController@edit')->name('addresses_form');
    Route::get('/addresses/form/{id}', 'AddressController@edit');
    Route::post('/addresses/form', 'AddressController@store');
    Route::post('/addresses/delete', 'AddressController@destroy')->name('addresses_destroy');
    Route::post('/addresses/exchange', 'AddressController@exchange')->name('addresses_exchange');

    Route::get('/products', 'ProductController@index')->name('products');
    Route::post('/products/json', 'ProductController@json')->name('products_json');
    Route::get('/products/form', 'ProductController@edit')->name('products_form');
    Route::get('/products/form/{id}', 'ProductController@edit');
    Route::post('/products/form', 'ProductController@store');
    Route::post('/products/delete', 'ProductController@destroy')->name('products_destroy');
    Route::post('/products/exchange', 'ProductController@exchange')->name('products_exchange');



}); /* Routes per la pagina di gestione per i vari form, aggiungere o eliminare gli elementi */

Route::get('/', 'SiteController@index')->name('home'); /* Route per la visualizzazione della home page */
Route::get('/menu', 'SiteController@menu')->name('menu'); /* route per i menu */
Route::get('/termini-e-condizioni', 'SiteController@termini')->name('termini-e-condizioni'); /* route dei termini e le condizioni */
Route::get('/menu/{slug}', 'SiteController@menu'); /* route per ??? */

Route::get('/cart_variations_form/{id}', 'SiteController@cart_variations_form');

Route::post('/products/json', 'ProductController@json')->name('products_json');




Route::get('/migrate', function () {
    Artisan::call("migrate");
    echo "done";
});

resources/views/cart_variations_form.blade.php
<form id="async" method="POST" enctype="multipart/form-data" > 
    {{ csrf_field() }} 

    <div class="row">   
        <input type="hidden" name="id_product" value="{{ $product->id }}">
        <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th>Prezzo</th>

                        <th style="width: 1px"></th>
                        <th style="width: 1px"></th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>
        
    </div>    
    <button class="d-none" id="click-me"></button>
</form>

resources/views/home.blade.php
@extends('layouts.front')



@section('content')

<div class="parallax-window"></div>

<div class="text-center p-2 border-bottom">

    {{$setting->under_banner}}

</div>

<h1 class="text-center pt-5">{{$setting->h1}}</h1>
<h2 class="text-center pb-5 font-weight-normal">{{$setting->h2}}</h2>


<div>
    <div class="container">
        <div class="card-columns">

            @foreach($news AS $new)

            <div class="card">
                @if($new->img)<img class="card-img-top" src="{{asset('news/'.$new->img)}}" alt="{{$new->title}}">@endif
                <div class="card-body">
                    <h5 class="card-title">{{$new->title}}</h5>
                    <h6><i>{{$new->sutitle}}</i></h6>
                    <div class="card-text text-justify"><small>{!!$new->text!!}</small></div>
                </div>
            </div>

            @endforeach
        </div>



    </div>
</div>



@endsection

resources/views/nostro_menu.blade.php
@extends('layouts.front')

@section('content')

<div>
    <div class="container">

        <div class="row font_vadodara_16px">

            <div class="col-sm-2 col_categories">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <h5 class="title_col_menu">Categorie</h5>
                    </li>
                    @if( $menu_categories!=null )
                        @for($i = 0; $i<(count($menu_categories)); $i++)
                            <li class="list-group-item list-group-flush border-0">
                                <a class="a_col_categories" href="#li_{{$i}}"><h6>{{ $menu_categories[$i] }}</h6></a>
                            </li>
                        @endfor
                    @else
                        <li class="list-group-item list-group-flush">
                            <a href="#">Menu vuoto</a>
                        </li>
                    @endif
                </ul>
                <br>
                <br>
            </div>
            <div class="overflow-scroll col-sm-7 col_menu">
                <div class="row col-12">
                    <div class="col-11">
                        <input class="form-control form-control-sm " type="text" placeholder="Cerca nel menu" aria-label="Cerca nel menu">
                    </div>
                    <div class="col-1">
                        <i class="fas fa-search" aria-hidden="true"></i>
                    </div>
                </div>
                <ul class="list-group smooth-scroll list-unstyled  list-group-flush">
                    @if( $menu_categories!=null )
                        @for($i = 0; $i<(count($menu_categories)); $i++)
                        <li id="li_{{$i}}" class="list-group-item list-group-flush"><button class="btn btn-link col_menu" data-toggle="collapse" data-target="#div_{{$i}}" aria-expanded="true" aria-controls="div_{{$i}}"><h5 class="title_col_menu">{{ $menu_categories[$i] }}</h5></button></li>
                            @for($j=0;$j<(count($category_products[$menu_categories[$i]]));$j++)
                                <li id="div_{{$i}}" class="list-group-item collapse show list-group-flush">
                                    <div class="row">
                                        @if($category_products[$menu_categories[$i]][$j]->img!=null)
                                        <div class="col-4"><img src="{{asset("images/".$category_products[$menu_categories[$i]][$j]->img)}}" class="img-fluid" alt="Responsive image"></div>
                                        @else
                                        <div class="col-4"><img src="{{asset("img/logo.png")}}" class="img-fluid" alt="Responsive image"></div>
                                        @endif
                                        <div class="row col-8">
                                            <div class="col-12">
                                                <h6 class="title_col_menu">{{ $category_products[$menu_categories[$i]][$j]->title }}</h6>
                                            </div>
                                            <div class="col-7">{{$category_products[$menu_categories[$i]][$j]->sutitle}}</div>
                                            <div class="col-3">{{$category_products[$menu_categories[$i]][$j]->price}} € </div>
                                            {{-- <div class="col-2"><button type="button" onclick="add_to_cart('{{$category_products[$menu_categories[$i]][$j]->id}}','{{ $category_products[$menu_categories[$i]][$j]->title }}','{{ $category_products[$menu_categories[$i]][$j]->price }}')" class="btn btn-primary b_add_product">+</button></div> --}}
                                            <div class="col-2"><a class="btn btn-outline-primary" href="">Aggiungi al carrello</a></div>
                                        </div>
                                    </div>
                                </li>
                            @endfor
                        @endfor
                    @else
                        <li class="list-group-item">
                                <a href="#">Menu vuoto</a>
                        </li>
                    @endif
                </ul>
                <br>
                <br>
            </div>

            <div class="col-sm-3 col_categories ">
                <br>
                <div><button type="button" class="btn btn-primary col-12">Ordina adesso</button></div>
                <input id="sub_totale" type="hidden" name="sub_totale">
                <input id="totale" type="hidden" name="totale" value="0">

                <ul id="ul_carrello" class="list-group list-group-flush ">
                    <li class="list-group-item list-group-flush">
                        <h5 class="title_col_menu">Carrello</h5>
                    </li>

                </ul>


                <ul id="ciao">

                </ul>

                <ul class="list-group list-group-flush ">
                    <li class="list-group-item list-group-flush border-top">
                        <h6 class="col_carrello"><span class="title_col_menu">Totale</span>  <span class="title_col_menu">€</span></h6>
                    </li>
                </ul>
                <br>
                <br>
            </div>
        </div>

        <div>
            <br>
        </div>
        <div class="modal fade" id="Modal" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog  modal-sm" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel"></h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        ...
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Chiudi</button>
                        <button type="button" class="btn btn-primary" onclick="$(this).hide().delay(1000).show(0); $('#click-me').click()">Conferma</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>



@endsection

<script>


    function add_to_cart(id,name,prezzo){

        var totale = 0;
        totale +=  parseFloat($('#totale').val());
        $('#totale').val(totale+parseFloat(prezzo));
        var riga = ' <li id="li_cart_'+id+'" class="list-group-item list-group-flush border-0 li_riga_carrello"> '+
                   '     <input type="hidden" id="id_prod_'+id+'" value="'+id+'">'+
                   '     <input type="hidden" id="totale_li_'+id+'" value="0">'+
                   '     <input type="hidden" id="nome_prod_'+id+'" value="'+name+'">'+
                   '     <div class="row">'+
                   '        <div class="col-2 elem_riga_carrello"><button type="button" onclick="remove_from_cart(\''+id+'\')" class="btn btn-primary b_del_product">-</button></div>'+
                   '        <div class="col-2 elem_riga_carrello"> <h6 class="col_carrello">1 x</h6> </div>'+
                   '        <div class="col-5 elem_riga_carrello"> <h6 class="col_carrello">'+name+'</h6> </div>'+
                   '        <div class="col-3 elem_riga_carrello"> <h6 class="col_carrello">'+prezzo+'€</h6> </div>'+
                   '     </div>'+
                   '     <div class="row">'+
                   '        <ul id="ul_variazioni_'+id+'" class="col-4 elem_riga_carrello"></div>'+
                   '        </ul>'+
                   '     </div>'+
                   '     <div class="row">'+
                   '        <div class="col-4 elem_riga_carrello"></div>'+
                   '        <div class="col-4 elem_riga_carrello"></div>'+
                   '        <div class="col-4 elem_riga_carrello"><button data-backdrop="static" data-toggle="modal" data-target="#Modal" type="button"'+
                   '               onclick="$(\'#Modal .modal-body\').load(\'../cart_variations_form/'+id+'\')"'+
                   '               class="btn btn-link elem_riga_carrello">Variazioni</button></div>'+
                   '     </div>'+
                   ' </li>';
        $('#ul_carrello').append(riga);
    }

    function prova(){
        document.getElementById("ciao").innerHTML = riga;
    }


    function remove_from_cart(id){
        $('#li_cart_'+id+'').remove();
    }

</script>

resources/views/prova.blade.php
@extends('layouts.admin')



@section('js')



<script>









    var table;

    $(document).ready(function () {



    $.fn.dataTable.moment('DD-MM-YYYY');

    table = $('#dataTable').DataTable({

 "ordering": false,

    language: {

    processing: "Caricamento in corso...",

            search: "Cerca:",

            lengthMenu: "Mostra _MENU_ elementi",

            info: "Mostra elementi da _START_ a _END_ su _TOTAL_ ",

            infoEmpty: "Mostra elementi da 0 a 0 su 0",

            infoFiltered: "(filtro su _MAX_ elementi totali)",

            infoPostFix: "",

            loadingRecords: "Caricamento in corso...",

            zeroRecords: "Nessun elemento da mostrare",

            emptyTable: "Nessun elemento da mostrare",

            paginate: {

            first: "Primo",

                    previous: "Precedente",

                    next: "Seguente",

                    last: "Ultimo"

            },



    },



            "columnDefs": [



            {"searchable": false, "orderable": false, targets: 2},

            {"searchable": false, "orderable": false, targets: 3},

            {"searchable": false, "orderable": false, targets: 4},

            {"searchable": false, "orderable": false, targets: 5}



            ],







            "order": [[1, "asc"]],

            "ajax": {

            "url": "{{route('admin.menues_json')}}",

                    "data": function (d){

                        d._token = "{{ csrf_token() }}"

                    },

                    "type": "POST"

            }

    });

    });</script>

@stop





@section('content')



<div class="card">

    <div class="card-header">

        <h3 class="card-title">Menu</h3>





        <button data-backdrop="static"  data-toggle="modal" data-target="#Modal" onclick="$('#Modal .modal-body').load('{{route('admin.menues_form')}}')" class="btn btn-primary btn-sm  btn-add float-right">aggiungi</button>







    </div>

    <!-- /.box-header -->

    <div class="card-body">

        <div class="table-responsive">

            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">

                <thead>

                    <tr>

                        <th>Number</th>

                        <th>Nome</th>

                        <th style="width: 1px"></th>

                        <th style="width: 1px"></th>

                        <th style="width: 1px"></th>

                        <th style="width: 1px"></th>

                    </tr>

                </thead>

                <tbody>

                </tbody>

            </table>

        </div>

    </div>

</div>



<div class="modal fade" id="Modal" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">

    <div class="modal-dialog  modal-lg" role="document">

        <div class="modal-content">

            <div class="modal-header">

                <h5 class="modal-title" id="exampleModalLabel"></h5>

                <button type="button" class="close" data-dismiss="modal" aria-label="Close">

                    <span aria-hidden="true">&times;</span>

                </button>

            </div>

            <div class="modal-body">

                ...

            </div>

            <div class="modal-footer">

                <button type="button" class="btn btn-secondary" data-dismiss="modal">Chiudi</button>

                <button type="button" class="btn btn-primary" onclick="$(this).hide().delay(1000).show(0); $('#images').removeAttr('required'); $('#click-me').click(); $('#images').prop('required',true);">Conferma</button>

            </div>

        </div>

    </div>

</div>















@endsection

resources/views/termini.blade.php
@extends('layouts.front')



@section('content')





<div>
    <div class="container">
        <div class="row">
            <div class="col-12 pt-5 pb-5">
                
                {!!$setting->conditions!!}
                
            </div>            
            
        </div>


    </div>
</div>



@endsection