routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::prefix('gestione')->name('admin.')->middleware('auth')->group(function () {
    Route::get('/', 'DashboardController@index')->name('home');

    Route::get('/settings', 'SettingController@index')->name('settings');
    Route::post('/settings', 'SettingController@save');

    Route::get('/menues', 'MenuController@index')->name('menues');
    Route::post('/menues/json', 'MenuController@json')->name('menues_json');
    Route::get('/menues/form', 'MenuController@edit')->name('menues_form');
    Route::get('/menues/form/{id}', 'MenuController@edit');
    Route::post('/menues/form', 'MenuController@store');
    Route::post('/menues/delete', 'MenuController@destroy')->name('menues_destroy');
    Route::post('/menues/exchange', 'MenuController@exchange')->name('menues_exchange');

    Route::get('/news', 'NewsController@index')->name('news');
    Route::post('/news/json', 'NewsController@json')->name('news_json');
    Route::get('/news/form', 'NewsController@edit')->name('news_form');
    Route::get('/news/form/{id}', 'NewsController@edit');
    Route::post('/news/form', 'NewsController@store');
    Route::post('/news/delete', 'NewsController@destroy')->name('news_destroy');
    Route::post('/news/exchange', 'NewsController@exchange')->name('news_exchange');

    Route::get('/categories', 'CategoryController@index')->name('categories');
    Route::post('/categories/json', 'CategoryController@json')->name('categories_json');
    Route::get('/categories/form', 'CategoryController@edit')->name('categories_form');
    Route::get('/categories/form/{id}', 'CategoryController@edit');
    Route::post('/categories/form', 'CategoryController@store');
    Route::post('/categories/delete', 'CategoryController@destroy')->name('categories_destroy');
    Route::post('/categories/exchange', 'CategoryController@exchange')->name('categories_exchange');

    Route::get('/printareas', 'PrintAreaController@index')->name('printareas');
    Route::post('/printareas/json', 'PrintAreaController@json')->name('printareas_json');
    Route::get('/printareas/form', 'PrintAreaController@edit')->name('printareas_form');
    Route::get('/printareas/form/{id}', 'PrintAreaController@edit');
    Route::post('/printareas/form', 'PrintAreaController@store');
    Route::post('/printareas/delete', 'PrintAreaController@destroy')->name('printareas_destroy');
    Route::post('/printareas/exchange', 'PrintAreaController@exchange')->name('printareas_exchange');


    Route::get('/vgroups', 'VgroupController@index')->name('vgroups');
    Route::post('/vgroups/json', 'VgroupController@json')->name('vgroups_json');
    Route::get('/vgroups/form', 'VgroupController@edit')->name('vgroups_form');
    Route::get('/vgroups/form/{id}', 'VgroupController@edit');
    Route::post('/vgroups/form', 'VgroupController@store');
    Route::post('/vgroups/delete', 'VgroupController@destroy')->name('vgroups_destroy');
    Route::post('/vgroups/exchange', 'VgroupController@exchange')->name('vgroups_exchange');

    Route::get('/variations', 'VariationController@index')->name('variations');
    Route::post('/variations/json', 'VariationController@json')->name('variations_json');
    Route::get('/variations/form', 'VariationController@edit')->name('variations_form');
    Route::get('/variations/form/{id}', 'VariationController@edit');
    Route::post('/variations/form', 'VariationController@store');
    Route::post('/variations/delete', 'VariationController@destroy')->name('variations_destroy');
    Route::post('/variations/exchange', 'VariationController@exchange')->name('variations_exchange');

    Route::get('/addons', 'AddonController@index')->name('addons');
    Route::post('/addons/json', 'AddonController@json')->name('addons_json');
    Route::get('/addons/form', 'AddonController@edit')->name('addons_form');
    Route::get('/addons/form/{id}', 'AddonController@edit');
    Route::post('/addons/form', 'AddonController@store');
    Route::post('/addons/delete', 'AddonController@destroy')->name('addons_destroy');
    Route::post('/addons/exchange', 'AddonController@exchange')->name('addons_exchange');

    Route::get('/timetables', 'TimetableController@index')->name('timetables');
    Route::post('/timetables/json', 'TimetableController@json')->name('timetables_json');
    Route::get('/timetables/form', 'TimetableController@edit')->name('timetables_form');
    Route::get('/timetables/form/{id}', 'TimetableController@edit');
    Route::post('/timetables/form', 'TimetableController@store');
    Route::post('/timetables/delete', 'TimetableController@destroy')->name('timetables_destroy');
    Route::post('/timetables/exchange', 'TimetableController@exchange')->name('timetables_exchange');

    Route::get('/addresses', 'AddressController@index')->name('addresses');
    Route::post('/addresses/json', 'AddressController@json')->name('addresses_json');
    Route::get('/addresses/form', 'AddressController@edit')->name('addresses_form');
    Route::get('/addresses/form/{id}', 'AddressController@edit');
    Route::post('/addresses/form', 'AddressController@store');
    Route::post('/addresses/delete', 'AddressController@destroy')->name('addresses_destroy');
    Route::post('/addresses/exchange', 'AddressController@exchange')->name('addresses_exchange');

    Route::get('/products', 'ProductController@index')->name('products');
    Route::post('/products/json', 'ProductController@json')->name('products_json');
    Route::get('/products/form', 'ProductController@edit')->name('products_form');
    Route::get('/products/form/{id}', 'ProductController@edit');
    Route::post('/products/form', 'ProductController@store');
    Route::post('/products/delete', 'ProductController@destroy')->name('products_destroy');
    Route::post('/products/exchange', 'ProductController@exchange')->name('products_exchange');



}); /* Routes per la pagina di gestione per i vari form, aggiungere o eliminare gli elementi */

Route::get('/', 'SiteController@index')->name('home'); /* Route per la visualizzazione della home page */
Route::get('/menu', 'SiteController@menu')->name('menu'); /* route per i menu */
Route::get('/termini-e-condizioni', 'SiteController@termini')->name('termini-e-condizioni'); /* route dei termini e le condizioni */
Route::get('/menu/{slug}', 'SiteController@menu'); /* route per ??? */

Route::get('/cart_variations_form/{id}', 'SiteController@cart_variations_form');

Route::post('/products/json', 'ProductController@json')->name('products_json');




Route::get('/migrate', function () {
    Artisan::call("migrate");
    echo "done";
});

resources/views/admin/addons.blade.php
@extends('layouts.admin')

@section('js')

<script>
    
    function exchange(id1, id2){
        $.post('{{route('admin.addons_exchange')}}', {id1:id1, id2:id2,  _token: "{{ csrf_token() }}"}, function(){
            table.ajax.reload(null, false);
        });
    }
    
    
    
    
    var table;
    $(document).ready(function () {
        
    $.fn.dataTable.moment('DD-MM-YYYY');
    table = $('#dataTable').DataTable({
 "ordering": false,
    language: {
    processing: "Caricamento in corso...",
            search: "Cerca:",
            lengthMenu: "Mostra _MENU_ elementi",
            info: "Mostra elementi da _START_ a _END_ su _TOTAL_ ",
            infoEmpty: "Mostra elementi da 0 a 0 su 0",
            infoFiltered: "(filtro su _MAX_ elementi totali)",
            infoPostFix: "",
            loadingRecords: "Caricamento in corso...",
            zeroRecords: "Nessun elemento da mostrare",
            emptyTable: "Nessun elemento da mostrare",
            paginate: {
            first: "Primo",
                    previous: "Precedente",
                    next: "Seguente",
                    last: "Ultimo"
            },
            
    },
     
            "columnDefs": [
                
            {"searchable": false, "orderable": false, targets: 2},
            {"searchable": false, "orderable": false, targets: 3},
            {"searchable": false, "orderable": false, targets: 4},
            {"searchable": false, "orderable": false, targets: 5}

            ],
            
            
            
            "order": [[1, "asc"]],
            "ajax": {
            "url": "{{route('admin.addons_json')}}",
                    "data": function (d){
                        d._token = "{{ csrf_token() }}"                        
                    },
                    "type": "POST"
            }
    });
    });</script>
@stop


@section('content')

<div class="card">
    <div class="card-header">
        <h3 class="card-title">Aggiunte</h3>  
        
        
        <button data-backdrop="static"  data-toggle="modal" data-target="#Modal" onclick="$('#Modal .modal-body').load('{{route('admin.addons_form')}}')" class="btn btn-primary btn-sm  btn-add float-right">aggiungi</button>
        
        
        
    </div>
    <!-- /.box-header -->
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Number</th>
                        <th>Nome</th>
                        <th>Prezzo Aggiunta</th>
                        <th>Prezzo Rimozione</th>
                        <th style="width: 1px"></th>
                        <th style="width: 1px"></th>
                        <th style="width: 1px"></th>
                        <th style="width: 1px"></th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="modal fade" id="Modal" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog  modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Chiudi</button>
                <button type="button" class="btn btn-primary" onclick="$(this).hide().delay(1000).show(0); $('#images').removeAttr('required'); $('#click-me').click(); $('#images').prop('required',true);">Conferma</button>
            </div>
        </div>
    </div>
</div>







@endsection

resources/views/admin/addons_form.blade.php
<form id="async" method="POST" enctype="multipart/form-data" >


    {!! csrf_field() !!}
    <div class="row">

        <div class="col-12">
            <label class="label label-primary">Nome</label>
            <input class="form-control" type="text" name="name" value="{{$item->name}}" required>
            <input class="form-control" type="hidden" name="id" value="{{$item->id}}">
            
        </div>
        
        <div class="col-6">
            <label class="label label-primary">Modifica prezzo per aggiunta (+)</label>
            <input class="form-control" type="number" step="0.01" min="0" name="price_add" value="{{$item->price_add}}">
        </div>    
        <div class="col-6">
            <label class="label label-primary">Modifica prezzo per rimozione (-)</label>
            <input class="form-control" type="number" step="0.01" min="0" name="price_remove" value="{{$item->price_remove}}">
        </div>    
        
    </div>


    <button class="d-none" id="click-me"></button>
</form>


<script>


    $(function () {
        

        $('#async').submit(function (e) {
            e.preventDefault();

            var formData = new FormData($(this)[0]);
            $.ajax({
                url: '{{route('admin.addons_form')}}',
                type: 'POST',
                data: formData,
                contentType: false,
                cache: false,
                processData: false,
                success: function (data)
                {
                    if (data.error) {

                        $(document).Toasts('create', {
                            title: 'Errore',
                            class: 'bg-danger',
                            autohide: true,
                            delay: 2000,
                            body: data.error
                        })



                    } else {
                        $("#Modal").modal('hide');
                        $("#Modal .close").click()
                        $(document).Toasts('create', {
                            title: 'Successo',
                            class: 'bg-success',
                            autohide: true,
                            delay: 2000,
                            body: 'Dati inseriti correttamente'
                        })

                        table.ajax.reload(null, false);
                    }
                }
            });
        });
    });
</script>

resources/views/admin/addresses.blade.php
@extends('layouts.admin')

@section('js')

<script>
    
    function exchange(id1, id2){
        $.post('{{route('admin.addresses_exchange')}}', {id1:id1, id2:id2,  _token: "{{ csrf_token() }}"}, function(){
            table.ajax.reload(null, false);
        });
    }
    
    
    
    
    var table;
    $(document).ready(function () {
        
    $.fn.dataTable.moment('DD-MM-YYYY');
    table = $('#dataTable').DataTable({
 "ordering": false,
    language: {
    processing: "Caricamento in corso...",
            search: "Cerca:",
            lengthNews: "Mostra _MENU_ elementi",
            info: "Mostra elementi da _START_ a _END_ su _TOTAL_ ",
            infoEmpty: "Mostra elementi da 0 a 0 su 0",
            infoFiltered: "(filtro su _MAX_ elementi totali)",
            infoPostFix: "",
            loadingRecords: "Caricamento in corso...",
            zeroRecords: "Nessun elemento da mostrare",
            emptyTable: "Nessun elemento da mostrare",
            paginate: {
            first: "Primo",
                    previous: "Precedente",
                    next: "Seguente",
                    last: "Ultimo"
            },
            
    },
     
            "columnDefs": [
                
            {"searchable": false, "orderable": false, targets: 2},
            {"searchable": false, "orderable": false, targets: 3},
            {"searchable": false, "orderable": false, targets: 4},
            {"searchable": false, "orderable": false, targets: 5}

            ],
            
            
            
            "order": [[1, "asc"]],
            "ajax": {
            "url": "{{route('admin.addresses_json')}}",
                    "data": function (d){
                        d._token = "{{ csrf_token() }}"                        
                    },
                    "type": "POST"
            }
    });
    });</script>
@stop


@section('content')

<div class="card">
    <div class="card-header">
        <h3 class="card-title">Indirizzi</h3>  
        
        
        <button data-backdrop="static"  data-toggle="modal" data-target="#Modal" onclick="$('#Modal .modal-body').load('{{route('admin.addresses_form')}}')" class="btn btn-primary btn-sm  btn-add float-right">aggiungi</button>
        
        
        
    </div>
    <!-- /.box-header -->
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Number</th>
                        <th>Nome</th>
                        <th style="width: 1px"></th>
                        <th style="width: 1px"></th>
                        <th style="width: 1px"></th>
                        <th style="width: 1px"></th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="modal fade" id="Modal" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog  modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Chiudi</button>
                <button type="button" class="btn btn-primary" onclick="$(this).hide().delay(1000).show(0); $('#images').removeAttr('required'); $('#click-me').click(); $('#images').prop('required',true);">Conferma</button>
            </div>
        </div>
    </div>
</div>







@endsection

resources/views/admin/dashboard.blade.php
@extends('layouts.admin')


@section('content')

ciao

@endsection

resources/views/admin/printareas.blade.php
@extends('layouts.admin')



@section('js')



<script>



    function exchange(id1, id2){

        $.post('{{route('admin.printareas_exchange')}}', {id1:id1, id2:id2,  _token: "{{ csrf_token() }}"}, function(){

            table.ajax.reload(null, false);

        });

    }









    var table;

    $(document).ready(function () {



    $.fn.dataTable.moment('DD-MM-YYYY');

    table = $('#dataTable').DataTable({

 "ordering": false,

    language: {

    processing: "Caricamento in corso...",

            search: "Cerca:",

            lengthNews: "Mostra _MENU_ elementi",

            info: "Mostra elementi da _START_ a _END_ su _TOTAL_ ",

            infoEmpty: "Mostra elementi da 0 a 0 su 0",

            infoFiltered: "(filtro su _MAX_ elementi totali)",

            infoPostFix: "",

            loadingRecords: "Caricamento in corso...",

            zeroRecords: "Nessun elemento da mostrare",

            emptyTable: "Nessun elemento da mostrare",

            paginate: {

            first: "Primo",

                    previous: "Precedente",

                    next: "Seguente",

                    last: "Ultimo"

            },



    },



            "columnDefs": [



            {"searchable": false, "orderable": false, targets: 2},

            {"searchable": false, "orderable": false, targets: 3},

            {"searchable": false, "orderable": false, targets: 4},

            {"searchable": false, "orderable": false, targets: 5},



            ],







            "order": [[1, "asc"]],

            "ajax": {

            "url": "{{route('admin.printareas_json')}}",

                    "data": function (d){

                        d._token = "{{ csrf_token() }}"

                    },

                    "type": "POST"

            }

    });

    });</script>

@stop





@section('content')



<div class="card">

    <div class="card-header">

        <h3 class="card-title">Aree Stampa</h3>





        <button data-backdrop="static"  data-toggle="modal" data-target="#Modal" onclick="$('#Modal .modal-body').load('{{route('admin.printareas_form')}}')" class="btn btn-primary btn-sm  btn-add float-right">aggiungi</button>







    </div>

    <!-- /.box-header -->

    <div class="card-body">

        <div class="table-responsive">

            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">

                <thead>

                    <tr>

                        <th>id</th>

                        <th>nome stampante</th>

                        <th>indirizzo ip</th>

                        <th>Copie di stampa</th>

                        <th style="width: 1px"></th>

                        <th style="width: 1px"></th>

                        <th style="width: 1px"></th>

                        <th style="width: 1px"></th>


                    </tr>

                </thead>

                <tbody>

                </tbody>

            </table>

        </div>

    </div>

</div>



<div class="modal fade" id="Modal" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">

    <div class="modal-dialog  modal-lg" role="document">

        <div class="modal-content">

            <div class="modal-header">

                <h5 class="modal-title" id="exampleModalLabel"></h5>

                <button type="button" class="close" data-dismiss="modal" aria-label="Close">

                    <span aria-hidden="true">&times;</span>

                </button>

            </div>

            <div class="modal-body">

                ...

            </div>

            <div class="modal-footer">

                <button type="button" class="btn btn-secondary" data-dismiss="modal">Chiudi</button>

                <button type="button" class="btn btn-primary" onclick="$(this).hide().delay(1000).show(0); $('#click-me').click();">Conferma</button>

            </div>

        </div>

    </div>

</div>















@endsection

resources/views/admin/products.blade.php
@extends('layouts.admin')

@section('js')

<script>
    
    function exchange(id1, id2){
        $.post('{{route('admin.products_exchange')}}', {id1:id1, id2:id2,  _token: "{{ csrf_token() }}"}, function(){
            table.ajax.reload(null, false);
        });
    }
    
    
    
    
    var table;
    $(document).ready(function () {
        
    $.fn.dataTable.moment('DD-MM-YYYY');
    table = $('#dataTable').DataTable({
 "ordering": false,
    language: {
    processing: "Caricamento in corso...",
            search: "Cerca:",
            lengthNews: "Mostra _MENU_ elementi",
            info: "Mostra elementi da _START_ a _END_ su _TOTAL_ ",
            infoEmpty: "Mostra elementi da 0 a 0 su 0",
            infoFiltered: "(filtro su _MAX_ elementi totali)",
            infoPostFix: "",
            loadingRecords: "Caricamento in corso...",
            zeroRecords: "Nessun elemento da mostrare",
            emptyTable: "Nessun elemento da mostrare",
            paginate: {
            first: "Primo",
                    previous: "Precedente",
                    next: "Seguente",
                    last: "Ultimo"
            },
            
    },
     
            "columnDefs": [
                
            {"searchable": false, "orderable": false, targets: 2},
            {"searchable": false, "orderable": false, targets: 3},
            {"searchable": false, "orderable": false, targets: 4},
            {"searchable": false, "orderable": false, targets: 5}

            ],
            
            
            
            "order": [[1, "asc"]],
            "ajax": {
            "url": "{{route('admin.products_json')}}",
                    "data": function (d){
                        d._token = "{{ csrf_token() }}"                        
                    },
                    "type": "POST"
            }
    });
    });</script>
@stop


@section('content')

<div class="card">
    <div class="card-header">
        <h3 class="card-title">Prodotti</h3>  
        
        
        <button data-backdrop="static"  data-toggle="modal" data-target="#Modal" onclick="$('#Modal .modal-body').load('{{route('admin.products_form')}}')" class="btn btn-primary btn-sm  btn-add float-right">aggiungi</button>
        
        
        
    </div>
    <!-- /.box-header -->
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Number</th>
                        <th>Nome</th>
                        <th style="width: 1px"></th>
                        <th style="width: 1px"></th>
                        <th style="width: 1px"></th>
                        <th style="width: 1px"></th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="modal fade" id="Modal" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog  modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Chiudi</button>
                <button type="button" class="btn btn-primary" onclick="$(this).hide().delay(1000).show(0); $('#images').removeAttr('required'); $('#click-me').click(); $('#images').prop('required',true);">Conferma</button>
            </div>
        </div>
    </div>
</div>







@endsection

resources/views/admin/vgroups.blade.php
@extends('layouts.admin')

@section('js')

<script>
    
    function exchange(id1, id2){
        $.post('{{route('admin.vgroups_exchange')}}', {id1:id1, id2:id2,  _token: "{{ csrf_token() }}"}, function(){
            table.ajax.reload(null, false);
        });
    }
    
    
    
    
    var table;
    $(document).ready(function () {
        
    $.fn.dataTable.moment('DD-MM-YYYY');
    table = $('#dataTable').DataTable({
 "ordering": false,
    language: {
    processing: "Caricamento in corso...",
            search: "Cerca:",
            lengthMenu: "Mostra _MENU_ elementi",
            info: "Mostra elementi da _START_ a _END_ su _TOTAL_ ",
            infoEmpty: "Mostra elementi da 0 a 0 su 0",
            infoFiltered: "(filtro su _MAX_ elementi totali)",
            infoPostFix: "",
            loadingRecords: "Caricamento in corso...",
            zeroRecords: "Nessun elemento da mostrare",
            emptyTable: "Nessun elemento da mostrare",
            paginate: {
            first: "Primo",
                    previous: "Precedente",
                    next: "Seguente",
                    last: "Ultimo"
            },
            
    },
     
            "columnDefs": [
                
            {"searchable": false, "orderable": false, targets: 2},
            {"searchable": false, "orderable": false, targets: 3},
            {"searchable": false, "orderable": false, targets: 4},
            {"searchable": false, "orderable": false, targets: 5}

            ],
            
            
            
            "order": [[1, "asc"]],
            "ajax": {
            "url": "{{route('admin.vgroups_json')}}",
                    "data": function (d){
                        d._token = "{{ csrf_token() }}"                        
                    },
                    "type": "POST"
            }
    });
    });</script>
@stop


@section('content')

<div class="card">
    <div class="card-header">
        <h3 class="card-title">Gruppi di Variazioni</h3>  
        
        
        <button data-backdrop="static"  data-toggle="modal" data-target="#Modal" onclick="$('#Modal .modal-body').load('{{route('admin.vgroups_form')}}')" class="btn btn-primary btn-sm  btn-add float-right">aggiungi</button>
        
        
        
    </div>
    <!-- /.box-header -->
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Number</th>
                        <th>Nome</th>
                        <th style="width: 1px"></th>
                        <th style="width: 1px"></th>
                        <th style="width: 1px"></th>
                        <th style="width: 1px"></th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="modal fade" id="Modal" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog  modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Chiudi</button>
                <button type="button" class="btn btn-primary" onclick="$(this).hide().delay(1000).show(0); $('#images').removeAttr('required'); $('#click-me').click(); $('#images').prop('required',true);">Conferma</button>
            </div>
        </div>
    </div>
</div>







@endsection